server:
  port: 8080
  session-timeout: 30
  tomcat:
    max-threads: 500
    uri-encoding: UTF-8

spring:
  application:
    name: vector-play
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp

pro:
  cardkey: 5/15/30/50/75/105/140/180/225/300/400/500/505/515/530/550/575/605/640/680/725/800/900/1000
  cardval: 0/1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24
  tokenkey: 3/8/15/25/37/52/70/100
  tokenval: 15/10/5/4/3/2/1/0

contract:
  path: D:/blockchain/nettest/ropsten/keystore/UTC--2018-04-22T08-28-10.946419400Z--d3ee6bbe053a2510a2ae8faf58ebabecebb624c3
  directory: D:/blockchain/nettest/ropsten/keystore
  password:

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: jdbc:mysql://192.168.138.157:3307/vector_play?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    initial-size: 5
    min-idle: 3
    max-active: 60000
    test-on-borrow: true
    validation-query : SELECT 'x' from DUAL
    filters[0]: config
    filters[1]: stat
    filters[2]: wall
  slave:
    url: jdbc:mysql://192.168.138.157:3307/vector_play?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    initial-size: 5
    min-idle: 3
    max-active: 60000
    test-on-borrow: true
    validation-query : SELECT 'x' from DUAL
    filters[0]: config
    filters[1]: stat
    filters[2]: wall

mybaits:
  configLocation : mybatis-config.xml
  path : \mapper\*.xml
  pageSqlId : .*Page$
  dialect : MYSQL